In [1]:
from sklearn import tree
import pandas as pd
import os

In [2]:
input_data_file = "top_ten_line_cnt.txt"
df = pd.read_csv(os.path.join("..", "Data", input_data_file),sep='\t')

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
#df = df.dropna()
df.head()

C:\Users\gleix\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (4,10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,npi,nppes_provider_gender,nppes_entity_code,nppes_provider_city,nppes_provider_zip,nppes_provider_state,nppes_provider_country,provider_type,medicare_participation_indicator,place_of_service,...,hcpcs_drug_indicator,line_srvc_cnt,bene_unique_cnt,bene_day_srvc_cnt,average_Medicare_allowed_amt,average_submitted_chrg_amt,average_Medicare_payment_amt,year,leie_code,leie
0,1437152196,F,I,MIAMI,331664653.0,FL,US,Podiatry,Y,O,...,N,91.0,54.0,91.0,75.910000,76.680000,60.730000,2012,1128a1,On_List
1,1790785277,M,I,OCEAN SPRINGS,395645803.0,MS,US,Gastroenterology,Y,O,...,N,511.0,326.0,511.0,64.546360,80.000000,46.697789,2012,1128a4,On_List
2,1952417610,M,I,HOUSTON,770812706.0,TX,US,Neurology,Y,O,...,N,309.0,282.0,309.0,72.852136,114.499191,55.423883,2014,1128a1,On_List
3,1376537977,M,I,DYERSBURG,380241899.0,TN,US,Family Practice,Y,O,...,N,63.0,41.0,63.0,65.750000,87.000000,29.795238,2012,1128b4,On_List
4,1043319866,M,I,SALINAS,939013901.0,CA,US,Cardiology,Y,O,...,N,286.0,232.0,286.0,75.870455,77.492832,52.149476,2014,1128a2,On_List

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5625898 entries, 0 to 5625897
Data columns (total 22 columns):
 #   Column                            Dtype
---  ------                            -----
 0   npi                               int64
 1   nppes_provider_gender             object
 2   nppes_entity_code                 object
 3   nppes_provider_city               object
 4   nppes_provider_zip                object
 5   nppes_provider_state              object
 6   nppes_provider_country            object
 7   provider_type                     object
 8   medicare_participation_indicator  object
 9   place_of_service                  object
 10  hcpcs_code                        object
 11  hcpcs_description                 object
 12  hcpcs_drug_indicator              object
 13  line_srvc_cnt                     float64
 14  bene_unique_cnt                   float64
 15  bene_day_srvc_cnt                 float64
 16  average_Medicare_allowed_amt      float64
 17  average_submitted_chrg_amt        float64
 18  average_Medicare_payment_amt      float64
 19  year                              int64
 20  leie_code                         object
 21  leie                              object
dtypes: float64(6), int64(2), object(14)
memory usage: 944.3+ MB

In [4]:
df.columns

Index(['npi', 'nppes_provider_gender', 'nppes_entity_code',
       'nppes_provider_city', 'nppes_provider_zip', 'nppes_provider_state',
       'nppes_provider_country', 'provider_type',
       'medicare_participation_indicator', 'place_of_service', 'hcpcs_code',
       'hcpcs_description', 'hcpcs_drug_indicator', 'line_srvc_cnt',
       'bene_unique_cnt', 'bene_day_srvc_cnt', 'average_Medicare_allowed_amt',
       'average_submitted_chrg_amt', 'average_Medicare_payment_amt', 'year',
       'leie_code', 'leie'],
      dtype='object')

In [5]:
df['nppes_provider_gender'] = df['nppes_provider_gender'].fillna('O')

In [6]:
#data = df.drop(['npi', 'nppes_provider_city', 'nppes_provider_zip', 'nppes_provider_state',              
#                'nppes_provider_country', 'provider_type', 'hcpcs_code', 'hcpcs_description', 'year', 'leie_code'], axis=1)

data = df.drop(['npi', 'nppes_provider_city', 'nppes_provider_zip', 'nppes_provider_state',              
                'nppes_provider_country', 'provider_type', 'hcpcs_description', 'year', 'leie_code'], axis=1)

data = data.dropna()
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5625898 entries, 0 to 5625897
Data columns (total 13 columns):
 #   Column                            Dtype
---  ------                            -----
 0   nppes_provider_gender             object
 1   nppes_entity_code                 object
 2   medicare_participation_indicator  object
 3   place_of_service                  object
 4   hcpcs_code                        object
 5   hcpcs_drug_indicator              object
 6   line_srvc_cnt                     float64
 7   bene_unique_cnt                   float64
 8   bene_day_srvc_cnt                 float64
 9   average_Medicare_allowed_amt      float64
 10  average_submitted_chrg_amt        float64
 11  average_Medicare_payment_amt      float64
 12  leie                              object
dtypes: float64(6), object(7)
memory usage: 600.9+ MB

In [7]:
disposition = data["leie"]
disposition_names = ["On_List", "Not"]
data1 = data.drop("leie", axis=1)
feature_names = data1.columns

In [8]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5625898 entries, 0 to 5625897
Data columns (total 12 columns):
 #   Column                            Dtype
---  ------                            -----
 0   nppes_provider_gender             object
 1   nppes_entity_code                 object
 2   medicare_participation_indicator  object
 3   place_of_service                  object
 4   hcpcs_code                        object
 5   hcpcs_drug_indicator              object
 6   line_srvc_cnt                     float64
 7   bene_unique_cnt                   float64
 8   bene_day_srvc_cnt                 float64
 9   average_Medicare_allowed_amt      float64
 10  average_submitted_chrg_amt        float64
 11  average_Medicare_payment_amt      float64
dtypes: float64(6), object(6)
memory usage: 558.0+ MB

In [9]:
disposition.shape

(5625898,)

In [10]:
test_df = data1.loc[(data["nppes_provider_gender"] == "O"), :]
test_df

,nppes_provider_gender,nppes_entity_code,medicare_participation_indicator,place_of_service,hcpcs_code,hcpcs_drug_indicator,line_srvc_cnt,bene_unique_cnt,bene_day_srvc_cnt,average_Medicare_allowed_amt,average_submitted_chrg_amt,average_Medicare_payment_amt
11570,O,O,N,O,99213,N,13.0,13.0,13.0,66.811538,77.307692,44.349231
41103,O,O,Y,O,99213,N,13.0,13.0,13.0,75.000000,75.000000,58.800000
46410,O,O,Y,O,99213,N,22.0,18.0,22.0,76.280000,90.000000,50.636818
59253,O,O,N,O,99213,N,30.0,24.0,30.0,69.040000,80.807667,43.626667
69539,O,O,N,O,99213,N,81.0,73.0,81.0,70.324938,74.038519,53.444321
...,...,...,...,...,...,...,...,...,...,...,...,...
5625892,O,O,Y,O,P9603,N,43.0,11.0,22.0,0.516744,14.179767,0.506512
5625893,O,O,Y,O,P9603,N,19661.4,302.0,713.0,1.010007,1.062944,0.989832
5625894,O,O,Y,F,P9603,N,1179.0,188.0,1179.0,1.015844,6.371391,0.995827
5625896,O,O,Y,O,P9603,N,23144.0,678.0,3014.0,0.949945,0.950060,0.930979
5625897,O,O,Y,O,P9603,N,4268.6,133.0,224.0,1.007101,1.027508,0.986954

In [11]:
new_data = pd.get_dummies(data1)
new_data

,line_srvc_cnt,bene_unique_cnt,bene_day_srvc_cnt,average_Medicare_allowed_amt,average_submitted_chrg_amt,average_Medicare_payment_amt,nppes_provider_gender_F,nppes_provider_gender_M,nppes_provider_gender_O,nppes_entity_code_I,...,hcpcs_code_36415,hcpcs_code_95004,hcpcs_code_A0425,hcpcs_code_G0471,hcpcs_code_J0585,hcpcs_code_J1071,hcpcs_code_P9603,hcpcs_code_Q0138,hcpcs_drug_indicator_N,hcpcs_drug_indicator_Y
0,91.0,54.0,91.0,75.910000,76.680000,60.730000,1,0,0,1,...,0,0,0,0,0,0,0,0,1,0
1,511.0,326.0,511.0,64.546360,80.000000,46.697789,0,1,0,1,...,0,0,0,0,0,0,0,0,1,0
2,309.0,282.0,309.0,72.852136,114.499191,55.423883,0,1,0,1,...,0,0,0,0,0,0,0,0,1,0
3,63.0,41.0,63.0,65.750000,87.000000,29.795238,0,1,0,1,...,0,0,0,0,0,0,0,0,1,0
4,286.0,232.0,286.0,75.870455,77.492832,52.149476,0,1,0,1,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5625893,19661.4,302.0,713.0,1.010007,1.062944,0.989832,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
5625894,1179.0,188.0,1179.0,1.015844,6.371391,0.995827,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
5625895,72053.0,191.0,1727.0,0.073811,0.075894,0.072338,0,1,0,1,...,0,0,0,0,0,0,1,0,1,0
5625896,23144.0,678.0,3014.0,0.949945,0.950060,0.930979,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
5625897,4268.6,133.0,224.0,1.007101,1.027508,0.986954,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0

In [12]:
new_data.columns

Index(['line_srvc_cnt', 'bene_unique_cnt', 'bene_day_srvc_cnt',
       'average_Medicare_allowed_amt', 'average_submitted_chrg_amt',
       'average_Medicare_payment_amt', 'nppes_provider_gender_F',
       'nppes_provider_gender_M', 'nppes_provider_gender_O',
       'nppes_entity_code_I', 'nppes_entity_code_O',
       'medicare_participation_indicator_N',
       'medicare_participation_indicator_Y', 'place_of_service_F',
       'place_of_service_O', 'hcpcs_code_36415', 'hcpcs_code_99213',
       'hcpcs_code_99214', 'hcpcs_code_36415', 'hcpcs_code_95004',
       'hcpcs_code_A0425', 'hcpcs_code_G0471', 'hcpcs_code_J0585',
       'hcpcs_code_J1071', 'hcpcs_code_P9603', 'hcpcs_code_Q0138',
       'hcpcs_drug_indicator_N', 'hcpcs_drug_indicator_Y'],
      dtype='object')

In [13]:
new_data = new_data.drop(['nppes_entity_code_O', 'medicare_participation_indicator_Y', 'place_of_service_O', 'hcpcs_drug_indicator_Y'], axis=1)
#new_data = new_data.drop(['nppes_entity_code_O', 'medicare_participation_indicator_Y', 'place_of_service_O'], axis=1)
new_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5625898 entries, 0 to 5625897
Data columns (total 24 columns):
 #   Column                              Dtype
---  ------                              -----
 0   line_srvc_cnt                       float64
 1   bene_unique_cnt                     float64
 2   bene_day_srvc_cnt                   float64
 3   average_Medicare_allowed_amt        float64
 4   average_submitted_chrg_amt          float64
 5   average_Medicare_payment_amt        float64
 6   nppes_provider_gender_F             uint8
 7   nppes_provider_gender_M             uint8
 8   nppes_provider_gender_O             uint8
 9   nppes_entity_code_I                 uint8
 10  medicare_participation_indicator_N  uint8
 11  place_of_service_F                  uint8
 12  hcpcs_code_36415                    uint8
 13  hcpcs_code_99213                    uint8
 14  hcpcs_code_99214                    uint8
 15  hcpcs_code_36415                    uint8
 16  hcpcs_code_95004                    uint8
 17  hcpcs_code_A0425                    uint8
 18  hcpcs_code_G0471                    uint8
 19  hcpcs_code_J0585                    uint8
 20  hcpcs_code_J1071                    uint8
 21  hcpcs_code_P9603                    uint8
 22  hcpcs_code_Q0138                    uint8
 23  hcpcs_drug_indicator_N              uint8
dtypes: float64(6), uint8(18)
memory usage: 397.0 MB

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(new_data, disposition, random_state=42)

In [15]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4219423 entries, 986780 to 1692743
Data columns (total 24 columns):
 #   Column                              Dtype
---  ------                              -----
 0   line_srvc_cnt                       float64
 1   bene_unique_cnt                     float64
 2   bene_day_srvc_cnt                   float64
 3   average_Medicare_allowed_amt        float64
 4   average_submitted_chrg_amt          float64
 5   average_Medicare_payment_amt        float64
 6   nppes_provider_gender_F             uint8
 7   nppes_provider_gender_M             uint8
 8   nppes_provider_gender_O             uint8
 9   nppes_entity_code_I                 uint8
 10  medicare_participation_indicator_N  uint8
 11  place_of_service_F                  uint8
 12  hcpcs_code_36415                    uint8
 13  hcpcs_code_99213                    uint8
 14  hcpcs_code_99214                    uint8
 15  hcpcs_code_36415                    uint8
 16  hcpcs_code_95004                    uint8
 17  hcpcs_code_A0425                    uint8
 18  hcpcs_code_G0471                    uint8
 19  hcpcs_code_J0585                    uint8
 20  hcpcs_code_J1071                    uint8
 21  hcpcs_code_P9603                    uint8
 22  hcpcs_code_Q0138                    uint8
 23  hcpcs_drug_indicator_N              uint8
dtypes: float64(6), uint8(18)
memory usage: 297.8 MB

In [16]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.9974844913702696

In [17]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9988218773885067

In [18]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.24508396963393006, 'hcpcs_drug_indicator'),
 (0.19745363807727434, 'hcpcs_code'),
 (0.18547829684015246, 'place_of_service'),
 (0.1436384308702607, 'nppes_entity_code'),
 (0.11363720258533683, 'nppes_provider_gender'),
 (0.1120189024979331, 'medicare_participation_indicator'),
 (0.0004771969238081262, 'average_Medicare_payment_amt'),
 (0.00036044262860239105, 'bene_unique_cnt'),
 (0.0003267286335711194, 'line_srvc_cnt'),
 (2.204312067956618e-05, 'average_Medicare_allowed_amt'),
 (2.036795029102521e-05, 'bene_day_srvc_cnt'),
 (1.533789056613299e-05, 'average_submitted_chrg_amt')]