In [1]:
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
import os
import pandas as pd
import numpy as np

# Read the CSV and Perform Basic Data Cleaning

In [2]:
input_data_file = "sort_data.txt"
df = pd.read_csv(os.path.join("..", "Data", input_data_file),sep='\t')
#df = pd.read_csv(os.path.join("..", "Data", input_data_file),sep='\t', nrows=150000)

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
#df = df.dropna()
df

C:\Users\gleix\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,npi,nppes_provider_gender,nppes_entity_code,nppes_provider_city,nppes_provider_zip,nppes_provider_state,nppes_provider_country,provider_type,medicare_participation_indicator,place_of_service,...,hcpcs_drug_indicator,line_srvc_cnt,bene_unique_cnt,bene_day_srvc_cnt,average_Medicare_allowed_amt,average_submitted_chrg_amt,average_Medicare_payment_amt,year,leie_code,leie
0,1205963402,M,I,ROCKVILLE,2.08521e+08,MD,US,Allergy/Immunology,Y,O,...,N,153.0,13.0,153.0,11.800000,25.000000,7.897516,2012,1128b4,On_List
1,1467447557,M,I,FLINT,4.85325e+08,MI,US,Family Practice,Y,O,...,N,93.0,65.0,93.0,129.454731,209.408602,97.705054,2017,1128a1,On_List
2,1952417610,M,I,HOUSTON,7.70813e+08,TX,US,Neurology,Y,O,...,N,36.0,35.0,36.0,40.992778,50.123611,25.856944,2014,1128a1,On_List
3,1467447557,M,I,FLINT,4.85325e+08,MI,US,Family Practice,Y,O,...,N,724.0,210.0,724.0,48.580000,150.000000,47.610000,2017,1128a1,On_List
4,1467447557,M,I,FLINT,4.85325e+08,MI,US,Family Practice,Y,O,...,N,11.0,11.0,11.0,25.000000,25.000000,6.985455,2017,1128a1,On_List
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56819222,1053396929,M,I,HACKENSACK,76011914,NJ,US,Diagnostic Radiology,Y,F,...,N,11.0,11.0,11.0,40.180000,75.000000,31.500000,2014,None,Not
56819223,1053396929,M,I,HACKENSACK,76011914,NJ,US,Diagnostic Radiology,Y,F,...,N,15.0,13.0,15.0,53.290000,160.000000,41.780000,2014,None,Not
56819224,1053396929,M,I,HACKENSACK,76011914,NJ,US,Diagnostic Radiology,Y,F,...,N,33.0,32.0,33.0,46.360000,151.000000,36.350000,2014,None,Not
56819225,1053396929,M,I,HACKENSACK,76011914,NJ,US,Diagnostic Radiology,Y,O,...,N,46.0,44.0,46.0,299.020000,525.000000,230.607391,2014,None,Not
56819226,1992999874,F,I,MECHANICSVILLE,231161844,VA,US,Internal Medicine,Y,F,...,N,49.0,49.0,49.0,107.980000,262.000000,123.950000,2017,None,Not

In [3]:
df['nppes_provider_gender'] = df['nppes_provider_gender'].fillna('O')

In [4]:
df.columns

Index(['npi', 'nppes_provider_gender', 'nppes_entity_code',
       'nppes_provider_city', 'nppes_provider_zip', 'nppes_provider_state',
       'nppes_provider_country', 'provider_type',
       'medicare_participation_indicator', 'place_of_service', 'hcpcs_code',
       'hcpcs_description', 'hcpcs_drug_indicator', 'line_srvc_cnt',
       'bene_unique_cnt', 'bene_day_srvc_cnt', 'average_Medicare_allowed_amt',
       'average_submitted_chrg_amt', 'average_Medicare_payment_amt', 'year',
       'leie_code', 'leie'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56819227 entries, 0 to 56819226
Data columns (total 22 columns):
 #   Column                            Dtype
---  ------                            -----
 0   npi                               int64
 1   nppes_provider_gender             object
 2   nppes_entity_code                 object
 3   nppes_provider_city               object
 4   nppes_provider_zip                object
 5   nppes_provider_state              object
 6   nppes_provider_country            object
 7   provider_type                     object
 8   medicare_participation_indicator  object
 9   place_of_service                  object
 10  hcpcs_code                        object
 11  hcpcs_description                 object
 12  hcpcs_drug_indicator              object
 13  line_srvc_cnt                     float64
 14  bene_unique_cnt                   float64
 15  bene_day_srvc_cnt                 float64
 16  average_Medicare_allowed_amt      float64
 17  average_submitted_chrg_amt        float64
 18  average_Medicare_payment_amt      float64
 19  year                              int64
 20  leie_code                         object
 21  leie                              object
dtypes: float64(6), int64(2), object(14)
memory usage: 9.3+ GB

# Select your features (columns)

In [6]:
# Set features. This will also be used as your x values.
selected_features = df[['line_srvc_cnt', 'place_of_service', 'hcpcs_drug_indicator', 'nppes_entity_code', 'nppes_provider_gender',
                       'medicare_participation_indicator', 'leie']]
selected_features = selected_features.dropna()
selected_features

,line_srvc_cnt,place_of_service,hcpcs_drug_indicator,nppes_entity_code,nppes_provider_gender,medicare_participation_indicator,leie
0,153.0,O,N,I,M,Y,On_List
1,93.0,O,N,I,M,Y,On_List
2,36.0,O,N,I,M,Y,On_List
3,724.0,O,N,I,M,Y,On_List
4,11.0,O,N,I,M,Y,On_List
...,...,...,...,...,...,...,...
56819222,11.0,F,N,I,M,Y,Not
56819223,15.0,F,N,I,M,Y,Not
56819224,33.0,F,N,I,M,Y,Not
56819225,46.0,O,N,I,M,Y,Not
56819226,49.0,F,N,I,F,Y,Not

# Create a Train Test Split

Use `koi_disposition` for the y values

In [7]:
selected_features.info()

#output_data_file = "mike_look_test.txt"
#selected_features.to_csv(os.path.join("..", "Data", output_data_file), index= False, sep='\t')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 56819221 entries, 0 to 56819226
Data columns (total 7 columns):
 #   Column                            Dtype
---  ------                            -----
 0   line_srvc_cnt                     float64
 1   place_of_service                  object
 2   hcpcs_drug_indicator              object
 3   nppes_entity_code                 object
 4   nppes_provider_gender             object
 5   medicare_participation_indicator  object
 6   leie                              object
dtypes: float64(1), object(6)
memory usage: 3.4+ GB

In [8]:
disposition = selected_features["leie"]
disposition_names = ["Not", "On_List"]
selected_features = selected_features.drop("leie", axis=1)
feature_names = selected_features.columns
selected_features.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 56819221 entries, 0 to 56819226
Data columns (total 6 columns):
 #   Column                            Dtype
---  ------                            -----
 0   line_srvc_cnt                     float64
 1   place_of_service                  object
 2   hcpcs_drug_indicator              object
 3   nppes_entity_code                 object
 4   nppes_provider_gender             object
 5   medicare_participation_indicator  object
dtypes: float64(1), object(5)
memory usage: 3.0+ GB

In [9]:
mike_df2 = disposition
mike3 = mike_df2.to_frame()
mike3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 56819221 entries, 0 to 56819226
Data columns (total 1 columns):
 #   Column  Dtype
---  ------  -----
 0   leie    object
dtypes: object(1)
memory usage: 867.0+ MB

In [10]:
mike3.leie.value_counts()

Not        56758899
On_List       60322
Name: leie, dtype: int64

In [11]:
data = pd.get_dummies(selected_features)
data

,line_srvc_cnt,place_of_service_F,place_of_service_O,hcpcs_drug_indicator_N,hcpcs_drug_indicator_Y,nppes_entity_code_I,nppes_entity_code_O,nppes_provider_gender_F,nppes_provider_gender_M,nppes_provider_gender_O,medicare_participation_indicator_N,medicare_participation_indicator_Y
0,153.0,0,1,1,0,1,0,0,1,0,0,1
1,93.0,0,1,1,0,1,0,0,1,0,0,1
2,36.0,0,1,1,0,1,0,0,1,0,0,1
3,724.0,0,1,1,0,1,0,0,1,0,0,1
4,11.0,0,1,1,0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
149995,12.0,0,1,1,0,1,0,0,1,0,0,1
149996,13.0,1,0,1,0,1,0,0,1,0,0,1
149997,11.0,0,1,1,0,1,0,0,1,0,0,1
149998,14.0,1,0,1,0,1,0,0,1,0,0,1
149999,16.0,0,1,1,0,1,0,0,1,0,0,1

In [12]:
data = data.drop(['nppes_entity_code_O', 'medicare_participation_indicator_Y', 'place_of_service_O', 'hcpcs_drug_indicator_Y'], axis=1)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 149999 entries, 0 to 149999
Data columns (total 8 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   line_srvc_cnt                       149999 non-null  float64
 1   place_of_service_F                  149999 non-null  uint8
 2   hcpcs_drug_indicator_N              149999 non-null  uint8
 3   nppes_entity_code_I                 149999 non-null  uint8
 4   nppes_provider_gender_F             149999 non-null  uint8
 5   nppes_provider_gender_M             149999 non-null  uint8
 6   nppes_provider_gender_O             149999 non-null  uint8
 7   medicare_participation_indicator_N  149999 non-null  uint8
dtypes: float64(1), uint8(7)
memory usage: 3.3 MB

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, disposition, random_state=42)

In [14]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112499 entries, 92989 to 121959
Data columns (total 8 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   line_srvc_cnt                       112499 non-null  float64
 1   place_of_service_F                  112499 non-null  uint8
 2   hcpcs_drug_indicator_N              112499 non-null  uint8
 3   nppes_entity_code_I                 112499 non-null  uint8
 4   nppes_provider_gender_F             112499 non-null  uint8
 5   nppes_provider_gender_M             112499 non-null  uint8
 6   nppes_provider_gender_O             112499 non-null  uint8
 7   medicare_participation_indicator_N  112499 non-null  uint8
dtypes: float64(1), uint8(7)
memory usage: 2.5 MB

In [15]:
y_train

92989         Not
43658     On_List
110699        Not
77131         Not
109217        Not
           ...
119880        Not
103695        Not
131933        Not
146868        Not
121959        Not
Name: leie, Length: 112499, dtype: object

In [16]:
# Support vector machine linear classifier
from sklearn.svm import SVC 
model = SVC(kernel='linear')

# Pre-processing
Scale the data using the MinMaxScaler and perform some feature selection

In [17]:
from sklearn.preprocessing import MinMaxScaler
X_minmax = MinMaxScaler().fit(X_train)

X_train_scale = X_minmax.transform(X_train)
X_test_scale = X_minmax.transform(X_test)

In [18]:
X_train_scale

array([[4.77868363e-07, 1.00000000e+00, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.77868363e-06, 0.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.97335454e-06, 0.00000000e+00, 0.00000000e+00, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.33803142e-05, 1.00000000e+00, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.74421953e-05, 0.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [6.69015708e-06, 1.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

# Hyperparameter Tuning
Use GridSearchCV to tune the model's parameters

In [19]:
# Create the GridSearch estimator along with a parameter object containing the values to adjust
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [1, 2],
              'gamma': [0.001, 0.01]}
grid = GridSearchCV(model, param_grid, verbose=3)

In [20]:
# Fit the model using the grid search estimator. 
# This will take the SVC model and try each combination of parameters
grid.fit(X_train_scale, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=0.652, total= 4.9min
[CV] C=1, gamma=0.001 ................................................

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  4.9min remaining:    0.0s

[CV] .................... C=1, gamma=0.001, score=0.658, total= 4.7min
[CV] C=1, gamma=0.001 ................................................

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  9.6min remaining:    0.0s

[CV] .................... C=1, gamma=0.001, score=0.654, total= 3.9min
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=0.650, total= 6.3min
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=0.661, total= 4.0min
[CV] C=1, gamma=0.01 .................................................
[CV] ..................... C=1, gamma=0.01, score=0.652, total= 5.3min
[CV] C=1, gamma=0.01 .................................................
[CV] ..................... C=1, gamma=0.01, score=0.658, total= 4.8min
[CV] C=1, gamma=0.01 .................................................
[CV] ..................... C=1, gamma=0.01, score=0.654, total= 3.6min
[CV] C=1, gamma=0.01 .................................................
[CV] ..................... C=1, gamma=0.01, score=0.650, total= 4.7min
[CV] C=1, gamma=0.01 .................................................
[CV] ..................... C=1, gamma=0.01, score=0.661, total= 3.8min
[CV] C=2, gamma=0.001 ................................................
[CV] .................... C=2, gamma=0.001, score=0.652, total= 4.1min
[CV] C=2, gamma=0.001 ................................................
[CV] .................... C=2, gamma=0.001, score=0.658, total= 5.3min
[CV] C=2, gamma=0.001 ................................................
[CV] .................... C=2, gamma=0.001, score=0.654, total= 5.0min
[CV] C=2, gamma=0.001 ................................................
[CV] .................... C=2, gamma=0.001, score=0.650, total= 3.9min
[CV] C=2, gamma=0.001 ................................................
[CV] .................... C=2, gamma=0.001, score=0.661, total= 3.3min
[CV] C=2, gamma=0.01 .................................................
[CV] ..................... C=2, gamma=0.01, score=0.652, total= 2.8min
[CV] C=2, gamma=0.01 .................................................
[CV] ..................... C=2, gamma=0.01, score=0.658, total= 3.5min
[CV] C=2, gamma=0.01 .................................................
[CV] ..................... C=2, gamma=0.01, score=0.654, total= 3.4min
[CV] C=2, gamma=0.01 .................................................
[CV] ..................... C=2, gamma=0.01, score=0.650, total= 3.2min
[CV] C=2, gamma=0.01 .................................................
[CV] ..................... C=2, gamma=0.01, score=0.661, total= 3.8min

[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed: 84.3min finished

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='linear', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [1, 2], 'gamma': [0.001, 0.01]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [21]:
print(f"Training Data Score: {grid.score(X_train_scale, y_train)}")
print(f"Testing Data Score: {grid.score(X_test_scale, y_test)}")

Training Data Score: 0.6552147130196713
Testing Data Score: 0.65712

In [22]:
# List the best parameters for this dataset
print(grid.best_params_)

{'C': 1, 'gamma': 0.001}

In [23]:
# List the best score
print(grid.best_score_)

0.6552147684588451

In [24]:
type(grid.cv_results_)

dict

In [25]:
print(grid.cv_results_.keys())

dict_keys(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time', 'param_C', 'param_gamma', 'params', 'split0_test_score', 'split1_test_score', 'split2_test_score', 'split3_test_score', 'split4_test_score', 'mean_test_score', 'std_test_score', 'rank_test_score'])

In [26]:
import pandas as pd

cv_results = pd.DataFrame(grid.cv_results_)
cv_results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,268.395916,53.179541,16.758980,1.435905,1,0.001,"{'C': 1, 'gamma': 0.001}",0.651867,0.658311,0.654311,0.650133,0.661452,0.655215,0.004155,1
1,250.040117,39.116601,16.608985,0.923451,1,0.01,"{'C': 1, 'gamma': 0.01}",0.651867,0.658311,0.654311,0.650133,0.661452,0.655215,0.004155,1
2,243.333989,42.349976,16.252746,3.718499,2,0.001,"{'C': 2, 'gamma': 0.001}",0.651867,0.658311,0.654311,0.650133,0.661452,0.655215,0.004155,1
3,187.379212,18.576933,12.949761,0.824766,2,0.01,"{'C': 2, 'gamma': 0.01}",0.651867,0.658311,0.654311,0.650133,0.661452,0.655215,0.004155,1

In [27]:
cv_results_tiny = cv_results[['param_C', 'param_gamma', 'mean_test_score']]
cv_results_tiny.sort_values(by='mean_test_score', ascending=False).head(50)

  param_C param_gamma  mean_test_score
0       1       0.001         0.655215
1       1        0.01         0.655215
2       2       0.001         0.655215
3       2        0.01         0.655215

In [28]:
# Best index for the model to impact the model.
print(grid.best_index_)

0

In [29]:
# Make predictions with the hypertuned model
predictions = grid.predict(X_test_scale)

In [30]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions,
                            target_names=["Not", "On_list"]))

              precision    recall  f1-score   support

         Not       0.77      0.61      0.68     22467
     On_list       0.56      0.72      0.63     15033

    accuracy                           0.66     37500
   macro avg       0.66      0.67      0.66     37500
weighted avg       0.68      0.66      0.66     37500

In [31]:
# save your model by updating "your_name" with your name
# and "your_model" with your model variable
# be sure to turn this in to BCS
# if joblib fails to import, try running the command to install in terminal/git-bash
import joblib
filename = 'Medicare_SVC_Grid_10-21-20_V2.sav'
joblib.dump(grid, filename)

['Medicare_SVC_Grid_10-21-20_V2.sav']

In [32]:
#from sklearn.metrics import f1_score

#f1_score(y_test, y_train, average='weighted', labels=np.unique(y_train))
#f1_score(y_test, y_train, average='weighted')

In [33]:
#from sklearn.metrics import f1_score

In [34]:
#predictions